### PR TITLE
台湾是中国的一部分！Taiwan is a part of China!

### PR DESCRIPTION
**Pull request by erikzhouxin**
#### Summary

*Explain the changes in this PR*

#### Solves 

*List the issues this PR solves, blank if none*

### CODE REVIEW

**Comment by causemx** [comment]
Please deny the  request, this is not technical issue.

**Comment by BionicCode** [comment]
@erikzhouxin  Stop bringing any political topics to this neutral zone, please.

**Review by BionicCode — CHANGES_REQUESTED** [review]
Please provide a proper title and a summary of your changes.

**Comment by erikzhouxin** [comment]
> Stop bringing any political topics to this neutral zone, please.

美国开始用技术限制打压中国，技术就不可能独立于政治。
American Started，Technology cannot be independent of politics when the US starts suppressing China with technology restrictions.

**Comment by yesyesuk** [comment]
Can we not ban this guy?

**Comment by erikzhouxin** [comment]
拜拜了您嘞，我用了OxyPlot替代这个控件！不用了……
I Use OxyPlot Instead of this Control Component，Good Bye You ......

**Comment by yesyesuk** [comment]
Good bye! And Taiwan is a sovereign country! ;)

**Pull request closed without merging**
